In [143]:
import pandas as pd

In [144]:
movies = pd.read_csv("dataset/tmdb_movies_data.csv")

In [146]:
movies.head()

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,5562,6.5,2015,137999939.3,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,6185,7.1,2015,137999939.3,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,2480,6.3,2015,101199955.5,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,5292,7.5,2015,183999919.0,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,2947,7.3,2015,174799923.1,1.385749e+09

In [147]:
movies.describe()

,id,popularity,budget,revenue,runtime,vote_count,vote_average,release_year,budget_adj,revenue_adj
count,10866.000000,10866.000000,1.086600e+04,1.086600e+04,10866.000000,10866.000000,10866.000000,10866.000000,1.086600e+04,1.086600e+04
mean,66064.177434,0.646441,1.462570e+07,3.982332e+07,102.070863,217.389748,5.974922,2001.322658,1.755104e+07,5.136436e+07
std,92130.136561,1.000185,3.091321e+07,1.170035e+08,31.381405,575.619058,0.935142,12.812941,3.430616e+07,1.446325e+08
min,5.000000,0.000065,0.000000e+00,0.000000e+00,0.000000,10.000000,1.500000,1960.000000,0.000000e+00,0.000000e+00
25%,10596.250000,0.207583,0.000000e+00,0.000000e+00,90.000000,17.000000,5.400000,1995.000000,0.000000e+00,0.000000e+00
50%,20669.000000,0.383856,0.000000e+00,0.000000e+00,99.000000,38.000000,6.000000,2006.000000,0.000000e+00,0.000000e+00
75%,75610.000000,0.713817,1.500000e+07,2.400000e+07,111.000000,145.750000,6.600000,2011.000000,2.085325e+07,3.369710e+07
max,417859.000000,32.985763,4.250000e+08,2.781506e+09,900.000000,9767.000000,9.200000,2015.000000,4.250000e+08,2.827124e+09

In [148]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10866 entries, 0 to 10865
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    10866 non-null  int64
 1   imdb_id               10856 non-null  object
 2   popularity            10866 non-null  float64
 3   budget                10866 non-null  int64
 4   revenue               10866 non-null  int64
 5   original_title        10866 non-null  object
 6   cast                  10790 non-null  object
 7   homepage              2936 non-null   object
 8   director              10822 non-null  object
 9   tagline               8042 non-null   object
 10  keywords              9373 non-null   object
 11  overview              10862 non-null  object
 12  runtime               10866 non-null  int64
 13  genres                10843 non-null  object
 14  production_companies  9836 non-null   object
 15  release_date          10866 non-null  object
 16  vote_count            10866 non-null  int64
 17  vote_average          10866 non-null  float64
 18  release_year          10866 non-null  int64
 19  budget_adj            10866 non-null  float64
 20  revenue_adj           10866 non-null  float64
dtypes: float64(4), int64(6), object(11)
memory usage: 1.7+ MB

In [149]:
movies.isna().sum()

id                         0
imdb_id                   10
popularity                 0
budget                     0
revenue                    0
original_title             0
cast                      76
homepage                7930
director                  44
tagline                 2824
keywords                1493
overview                   4
runtime                    0
genres                    23
production_companies    1030
release_date               0
vote_count                 0
vote_average               0
release_year               0
budget_adj                 0
revenue_adj                0
dtype: int64

In [150]:
movies = movies.dropna(subset=['genres'])

In [151]:
null_keywords = movies[movies["keywords"].isna() == True]
null_keywords["keywords"] = null_keywords["genres"]
null_keywords

C:\Users\s7522\AppData\Local\Temp\ipykernel_22044\4193119477.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  null_keywords["keywords"] = null_keywords["genres"]

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
130,245706,tt2273657,1.284541,0,4719695,True Story,Jonah Hill|James Franco|Felicity Jones|Maria D...,NaN,Rupert Goold,Some mysteries are beyond belief.,...,A drama centered around the relationship betwe...,100,Crime|Drama|Mystery,Plan B Entertainment|Regency Enterprises|New R...,4/17/2015,354,6.0,2015,0.000000e+00,4.342117e+06
149,346808,tt3181776,1.041922,20000000,0,Momentum,Olga Kurylenko|Morgan Freeman|James Purefoy|Je...,NaN,Stephen S. Campanelli,NaN,...,"When Alex, an infiltration expert with a secre...",96,Thriller|Action,Thaba Media|Azari Media,8/1/2015,100,5.8,2015,1.839999e+07,0.000000e+00
154,314405,tt3278330,1.008474,12000000,0,Il racconto dei racconti,Salma Hayek|Vincent Cassel|John C. Reilly|Toby...,NaN,Matteo Garrone,Desire. Envy. Obsession.,...,"A fantasy film with horror elements, ""The Tale...",125,Romance|Fantasy|Horror,HanWay Films|Rai Cinema|Le Pacte|Fonds Eurimag...,5/14/2015,211,5.7,2015,1.104000e+07,0.000000e+00
155,282984,tt3715320,1.007054,11000000,27391084,Irrational Man,Emma Stone|Joaquin Phoenix|Jamie Blackley|Park...,http://www.sonyclassics.com/irrationalman/,Woody Allen,NaN,...,"On a small town college campus, a philosophy p...",95,Mystery|Drama,Sony Pictures|Gravier Productions,7/17/2015,319,6.1,2015,1.012000e+07,2.519979e+07
160,304372,tt3862750,0.950793,12000000,60273173,The Perfect Guy,Michael Ealy|Sanaa Lathan|Morris Chestnut|Kath...,http://www.sonypictures.com/movies/theperfectguy/,David M. Rosenthal,"Trust one, fear the other.",...,Leah Vaughn appears to have the ideal life. Sh...,100,Drama|Thriller,Screen Gems,9/11/2015,122,5.6,2015,1.104000e+07,5.545129e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10753,19307,tt0064133,0.021121,0,0,Carry On Camping,Sid James|Charles Hawtrey|Joan Sims|Kenneth Wi...,NaN,Gerald Thomas,Fun and games in the great outdoors!,...,Sid and Bernie keep having their amorous inten...,88,Comedy,The Rank Organisation,5/29/1969,11,6.4,1969,0.000000e+00,0.000000e+00
10777,28932,tt0077531,0.439210,11,11,F.I.S.T.,Sylvester Stallone|Rod Steiger|Peter Boyle|Mel...,NaN,Norman Jewison,NaN,...,Johnny Kovak joins the Teamsters trade-union i...,145,Drama|Action,chateau productions,4/26/1978,13,6.7,1978,3.676971e+01,3.676971e+01
10787,14822,tt0078158,0.282763,0,16393000,Return From Witch Mountain,Bette Davis|Christopher Lee|Kim Richards|Ike E...,NaN,John Hough,Sinister forces from this world against two yo...,...,"In this sequal to ""Escape From Witch Mountain,...",95,Adventure|Fantasy|Science Fiction|Family,NaN,3/10/1978,22,5.8,1978,0.000000e+00,5.479689e+07
10811,40081,tt0077292,0.108201,0,0,Can que,Chen Kuan-Tai|Philip Kwok Chun-Fung|Lo Meng|Su...,NaN,Chang Cheh,NaN,...,Crippled Avengers is a 1978 Shaw Brothers kung...,100,Action|Drama|Foreign,Shaw Brothers,12/20/1978,11,7.5,1978,0.000000e+00,0.000000e+00
10842,36540,tt0061199,0.253437,0,0,Winnie the Pooh and the Honey Tree,Sterling Holloway|Junius Matthews|Sebastian Ca...,NaN,Wolfgang Reitherman,NaN,...,Christopher Robin's bear attempts to raid a be...,25,Animation|Family,NaN,1/1/1966,12,7.9,1966,0.000000e+00,0.000000e+00

In [152]:
movies = pd.merge(movies, null_keywords, how = 'outer')
movies

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,5562,6.5,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,6185,7.1,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,2480,6.3,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,5292,7.5,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,2947,7.3,2015,1.747999e+08,1.385749e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12313,19307,tt0064133,0.021121,0,0,Carry On Camping,Sid James|Charles Hawtrey|Joan Sims|Kenneth Wi...,NaN,Gerald Thomas,Fun and games in the great outdoors!,...,Sid and Bernie keep having their amorous inten...,88,Comedy,The Rank Organisation,5/29/1969,11,6.4,1969,0.000000e+00,0.000000e+00
12314,28932,tt0077531,0.439210,11,11,F.I.S.T.,Sylvester Stallone|Rod Steiger|Peter Boyle|Mel...,NaN,Norman Jewison,NaN,...,Johnny Kovak joins the Teamsters trade-union i...,145,Drama|Action,chateau productions,4/26/1978,13,6.7,1978,3.676971e+01,3.676971e+01
12315,14822,tt0078158,0.282763,0,16393000,Return From Witch Mountain,Bette Davis|Christopher Lee|Kim Richards|Ike E...,NaN,John Hough,Sinister forces from this world against two yo...,...,"In this sequal to ""Escape From Witch Mountain,...",95,Adventure|Fantasy|Science Fiction|Family,NaN,3/10/1978,22,5.8,1978,0.000000e+00,5.479689e+07
12316,40081,tt0077292,0.108201,0,0,Can que,Chen Kuan-Tai|Philip Kwok Chun-Fung|Lo Meng|Su...,NaN,Chang Cheh,NaN,...,Crippled Avengers is a 1978 Shaw Brothers kung...,100,Action|Drama|Foreign,Shaw Brothers,12/20/1978,11,7.5,1978,0.000000e+00,0.000000e+00
12317,36540,tt0061199,0.253437,0,0,Winnie the Pooh and the Honey Tree,Sterling Holloway|Junius Matthews|Sebastian Ca...,NaN,Wolfgang Reitherman,NaN,...,Christopher Robin's bear attempts to raid a be...,25,Animation|Family,NaN,1/1/1966,12,7.9,1966,0.000000e+00,0.000000e+00

In [153]:
movies = movies.dropna(subset=['keywords'])
movies

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,5562,6.5,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,6185,7.1,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,2480,6.3,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,5292,7.5,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,2947,7.3,2015,1.747999e+08,1.385749e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12313,19307,tt0064133,0.021121,0,0,Carry On Camping,Sid James|Charles Hawtrey|Joan Sims|Kenneth Wi...,NaN,Gerald Thomas,Fun and games in the great outdoors!,...,Sid and Bernie keep having their amorous inten...,88,Comedy,The Rank Organisation,5/29/1969,11,6.4,1969,0.000000e+00,0.000000e+00
12314,28932,tt0077531,0.439210,11,11,F.I.S.T.,Sylvester Stallone|Rod Steiger|Peter Boyle|Mel...,NaN,Norman Jewison,NaN,...,Johnny Kovak joins the Teamsters trade-union i...,145,Drama|Action,chateau productions,4/26/1978,13,6.7,1978,3.676971e+01,3.676971e+01
12315,14822,tt0078158,0.282763,0,16393000,Return From Witch Mountain,Bette Davis|Christopher Lee|Kim Richards|Ike E...,NaN,John Hough,Sinister forces from this world against two yo...,...,"In this sequal to ""Escape From Witch Mountain,...",95,Adventure|Fantasy|Science Fiction|Family,NaN,3/10/1978,22,5.8,1978,0.000000e+00,5.479689e+07
12316,40081,tt0077292,0.108201,0,0,Can que,Chen Kuan-Tai|Philip Kwok Chun-Fung|Lo Meng|Su...,NaN,Chang Cheh,NaN,...,Crippled Avengers is a 1978 Shaw Brothers kung...,100,Action|Drama|Foreign,Shaw Brothers,12/20/1978,11,7.5,1978,0.000000e+00,0.000000e+00
12317,36540,tt0061199,0.253437,0,0,Winnie the Pooh and the Honey Tree,Sterling Holloway|Junius Matthews|Sebastian Ca...,NaN,Wolfgang Reitherman,NaN,...,Christopher Robin's bear attempts to raid a be...,25,Animation|Family,NaN,1/1/1966,12,7.9,1966,0.000000e+00,0.000000e+00

In [154]:
num_vals = ["budget", "runtime", "budget_adj"]
for col in num_vals:
    movies[col].replace(0, movies[col].mean(), inplace=True)

C:\Users\s7522\AppData\Local\Temp\ipykernel_22044\2443092715.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies[col].replace(0, movies[col].mean(), inplace=True)

In [155]:
movies

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,1.500000e+08,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124.0,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,5562,6.5,2015,1.379999e+08,1.392446e+09
1,76341,tt1392190,28.419936,1.500000e+08,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120.0,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,6185,7.1,2015,1.379999e+08,3.481613e+08
2,262500,tt2908446,13.112507,1.100000e+08,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119.0,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,2480,6.3,2015,1.012000e+08,2.716190e+08
3,140607,tt2488496,11.173104,2.000000e+08,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136.0,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,5292,7.5,2015,1.839999e+08,1.902723e+09
4,168259,tt2820852,9.335014,1.900000e+08,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137.0,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,2947,7.3,2015,1.747999e+08,1.385749e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12313,19307,tt0064133,0.021121,1.465672e+07,0,Carry On Camping,Sid James|Charles Hawtrey|Joan Sims|Kenneth Wi...,NaN,Gerald Thomas,Fun and games in the great outdoors!,...,Sid and Bernie keep having their amorous inten...,88.0,Comedy,The Rank Organisation,5/29/1969,11,6.4,1969,1.758827e+07,0.000000e+00
12314,28932,tt0077531,0.439210,1.100000e+01,11,F.I.S.T.,Sylvester Stallone|Rod Steiger|Peter Boyle|Mel...,NaN,Norman Jewison,NaN,...,Johnny Kovak joins the Teamsters trade-union i...,145.0,Drama|Action,chateau productions,4/26/1978,13,6.7,1978,3.676971e+01,3.676971e+01
12315,14822,tt0078158,0.282763,1.465672e+07,16393000,Return From Witch Mountain,Bette Davis|Christopher Lee|Kim Richards|Ike E...,NaN,John Hough,Sinister forces from this world against two yo...,...,"In this sequal to ""Escape From Witch Mountain,...",95.0,Adventure|Fantasy|Science Fiction|Family,NaN,3/10/1978,22,5.8,1978,1.758827e+07,5.479689e+07
12316,40081,tt0077292,0.108201,1.465672e+07,0,Can que,Chen Kuan-Tai|Philip Kwok Chun-Fung|Lo Meng|Su...,NaN,Chang Cheh,NaN,...,Crippled Avengers is a 1978 Shaw Brothers kung...,100.0,Action|Drama|Foreign,Shaw Brothers,12/20/1978,11,7.5,1978,1.758827e+07,0.000000e+00
12317,36540,tt0061199,0.253437,1.465672e+07,0,Winnie the Pooh and the Honey Tree,Sterling Holloway|Junius Matthews|Sebastian Ca...,NaN,Wolfgang Reitherman,NaN,...,Christopher Robin's bear attempts to raid a be...,25.0,Animation|Family,NaN,1/1/1966,12,7.9,1966,1.758827e+07,0.000000e+00

In [156]:
def replace_char(text):
    if "|" in text:
        text = text.lower()
        text = text.replace("|", " ")
    return text

movies["genres"] = movies["genres"].apply(replace_char)
movies["keywords"] = movies["keywords"].apply(replace_char)
movies["tags"] = movies["genres"] + movies["keywords"]
movies_cpy = movies
movies = movies.drop(columns = ["cast","homepage","director","cast", "release_date", "revenue_adj","imdb_id","revenue","tagline","overview", "production_companies", "original_title", "release_year"])
movies_cpy = movies_cpy[["id", "original_title", "tags"]]
movies = movies.drop(columns =["keywords", "genres"])

C:\Users\s7522\AppData\Local\Temp\ipykernel_22044\742895274.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["genres"] = movies["genres"].apply(replace_char)
C:\Users\s7522\AppData\Local\Temp\ipykernel_22044\742895274.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["keywords"] = movies["keywords"].apply(replace_char)
C:\Users\s7522\AppData\Local\Temp\ipykernel_22044\742895274.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies["tags"] = movies["genres"] + movies["keywords"]

In [157]:
movies

,id,popularity,budget,runtime,vote_count,vote_average,budget_adj,tags
0,135397,32.985763,1.500000e+08,124.0,5562,6.5,1.379999e+08,action adventure science fiction thrillermonst...
1,76341,28.419936,1.500000e+08,120.0,6185,7.1,1.379999e+08,action adventure science fiction thrillerfutur...
2,262500,13.112507,1.100000e+08,119.0,2480,6.3,1.012000e+08,adventure science fiction thrillerbased on nov...
3,140607,11.173104,2.000000e+08,136.0,5292,7.5,1.839999e+08,action adventure science fiction fantasyandroi...
4,168259,9.335014,1.900000e+08,137.0,2947,7.3,1.747999e+08,action crime thrillercar race speed revenge su...
...,...,...,...,...,...,...,...,...
12313,19307,0.021121,1.465672e+07,88.0,11,6.4,1.758827e+07,ComedyComedy
12314,28932,0.439210,1.100000e+01,145.0,13,6.7,3.676971e+01,drama actiondrama action
12315,14822,0.282763,1.465672e+07,95.0,22,5.8,1.758827e+07,adventure fantasy science fiction familyadvent...
12316,40081,0.108201,1.465672e+07,100.0,11,7.5,1.758827e+07,action drama foreignaction drama foreign
12317,36540,0.253437,1.465672e+07,25.0,12,7.9,1.758827e+07,animation familyanimation family

In [158]:
movies_cpy

,id,original_title,tags
0,135397,Jurassic World,action adventure science fiction thrillermonst...
1,76341,Mad Max: Fury Road,action adventure science fiction thrillerfutur...
2,262500,Insurgent,adventure science fiction thrillerbased on nov...
3,140607,Star Wars: The Force Awakens,action adventure science fiction fantasyandroi...
4,168259,Furious 7,action crime thrillercar race speed revenge su...
...,...,...,...
12313,19307,Carry On Camping,ComedyComedy
12314,28932,F.I.S.T.,drama actiondrama action
12315,14822,Return From Witch Mountain,adventure fantasy science fiction familyadvent...
12316,40081,Can que,action drama foreignaction drama foreign
12317,36540,Winnie the Pooh and the Honey Tree,animation familyanimation family

In [168]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer()
vector = tf.fit_transform(movies["tags"].values.astype('U')).toarray()
vector

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [169]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vector)
similarity

array([[1.        , 0.11171674, 0.09162839, ..., 0.18796692, 0.03021971,
        0.        ],
       [0.11171674, 1.        , 0.19901162, ..., 0.21463365, 0.03450696,
        0.        ],
       [0.09162839, 0.19901162, 1.        , ..., 0.21069357, 0.        ,
        0.        ],
       ...,
       [0.18796692, 0.21463365, 0.21069357, ..., 1.        , 0.        ,
        0.09853247],
       [0.03021971, 0.03450696, 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.09853247, 0.        ,
        1.        ]])

In [170]:
distance = sorted(list(enumerate(similarity[2])), reverse= True, key = lambda vector : vector[1])

In [171]:
for i in distance[0:5]:
    print(movies_cpy.iloc[i[0]].original_title)

Insurgent
Divergent
Sleeper
Paranoia
Manborg

In [202]:
def recommand(movies):
    index = movies_cpy[movies_cpy["original_title"] == movies].index[0]
    distance = sorted(list(enumerate(similarity[index])), reverse= True, key = lambda vector : vector[1])
    for i in distance[0:5]:
        print(movies_cpy.iloc[i[0]].original_title)

In [203]:
recommand("Iron Man 3")

Superman Returns
Superman II
Man of Steel
Superman
Superman III